version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py

site_name: Test
nav:
   - 'index.rst'
   - 'glossary.md'
   - 'Subject1':
     - 'dir/file1.md'
     - 'dir/file2.md'
   - 'Subject2':
     - 'NestedSubject2_1':
       - 'dir/file1.md'
       - 'dir/file2.md'
theme:
    name: readthedocs
    include_homepage_in_sidebar: false
    highlightjs: true
    hijs_languages:
        - lua
