[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "LimeOS API"
authors = [{name = "Happygamer1983", email = "limeos.roblox@gmail.com"}]
dynamic = ["version", "description"]
